export var moredata = [
    {
        id:1,
        name:"jadav",
        salary:"10,000"
    },
    {
        id:2,
        name:"jaydeep",
        salary:"12,000"
    },
    {
        id:3,
        name:"kanzariya",
        salary:"14,000"
    },
    {
        id:4,
        name:"nilesh",
        salary:"16,000"
    },
    {
        id:5,
        name:"dharmesh",
        salary:"18,000"
    }
]